    /*
    * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
    * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
    */
    package admin;
    import com.mycompany.tindaklanjutku.Koneksi;
    import admin.tugas;
    import java.sql.Statement;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.util.Date;
    import javax.swing.JOptionPane;


    /**
     *
     * @author ASUS VIVO
     */
    public class EditTugas extends javax.swing.JFrame {

        private String username;
        public EditTugas(int idTugas, String username) {
            this.username = username;
            this.idTugas = idTugas;
            initComponents();
            loadTugasData(); // Memuat data tugas berdasarkan ID
            setLocationRelativeTo(null); // Tampil di tengah layar
        }
    private int idTugas;

        private void loadTugasData() {
            try (Connection conn = Koneksi.configDB();
                PreparedStatement pstmt = conn.prepareStatement(
                    "SELECT judul, deskripsi, deadline, k.nama_kategori " +
                    "FROM tugas t JOIN kategori k ON t.id_kategori = k.id_kategori " +
                    "WHERE t.id_tugas = ?")) {

                pstmt.setInt(1, idTugas);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    judulField.setText(rs.getString("judul"));
                    deskripsiField.setText(rs.getString("deskripsi"));
                    dateDeadline.setDate(rs.getDate("deadline"));
                    kategori1.setText(rs.getString("nama_kategori"));
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal memuat data tugas: " + e.getMessage());
            }
        }







        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustom1 = new com.mycompany.tindaklanjutku.custom.panelCustom();
        panelCustom2 = new com.mycompany.tindaklanjutku.custom.panelCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        judulField = new com.mycompany.tindaklanjutku.custom.RoundedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deskripsiField = new com.mycompany.tindaklanjutku.custom.RoundedTextField();
        dateDeadline = new com.toedter.calendar.JDateChooser();
        roundedButton3 = new com.mycompany.tindaklanjutku.custom.RoundedButton();
        kategori1 = new com.mycompany.tindaklanjutku.custom.RoundedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Tugas Admin");

        panelCustom1.setBackground(new java.awt.Color(78, 75, 209));
        panelCustom1.setRoundBottomLeft(8);
        panelCustom1.setRoundBottomRight(8);
        panelCustom1.setRoundTopLeft(8);
        panelCustom1.setRoundTopRight(8);

        panelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom2.setRoundBottomLeft(12);
        panelCustom2.setRoundBottomRight(12);
        panelCustom2.setRoundTopLeft(12);
        panelCustom2.setRoundTopRight(12);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 75, 209));
        jLabel1.setText("Edit Tugas");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Judul       :");

        judulField.setBackground(new java.awt.Color(255, 255, 255));
        judulField.setForeground(new java.awt.Color(51, 51, 51));
        judulField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Deskripsi :");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Deadline :");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Kategori :");

        deskripsiField.setBackground(new java.awt.Color(255, 255, 255));
        deskripsiField.setForeground(new java.awt.Color(51, 51, 51));
        deskripsiField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        dateDeadline.setBackground(new java.awt.Color(255, 255, 255));
        dateDeadline.setForeground(new java.awt.Color(255, 255, 255));

        roundedButton3.setBackground(new java.awt.Color(0, 204, 0));
        roundedButton3.setText("simpan");
        roundedButton3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        roundedButton3.setHoverBackgroundColor(new java.awt.Color(0, 255, 51));
        roundedButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton3ActionPerformed(evt);
            }
        });

        kategori1.setBackground(new java.awt.Color(255, 255, 255));
        kategori1.setForeground(new java.awt.Color(51, 51, 51));
        kategori1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                        .addComponent(roundedButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                        .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCustom2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCustom2Layout.createSequentialGroup()
                                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCustom2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(dateDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelCustom2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(kategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(deskripsiField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(panelCustom2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(deskripsiField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dateDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(69, 69, 69)
                .addComponent(roundedButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void roundedButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton3ActionPerformed
            String judul = judulField.getText();
            String deskripsi = deskripsiField.getText();
            Date deadline = dateDeadline.getDate();
            String kategoriStr = kategori1.getText().trim();

            if (judul.isEmpty() || deskripsi.isEmpty() || deadline == null || kategoriStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
                return;
            }

            Connection conn = null;
            try {
                conn = Koneksi.configDB();
                conn.setAutoCommit(false); // Mulai transaksi

                // Cek kategori
                String cekKategori = "SELECT id_kategori FROM kategori WHERE nama_kategori = ?";
                PreparedStatement cekStmt = conn.prepareStatement(cekKategori);
                cekStmt.setString(1, kategoriStr);
                ResultSet rs = cekStmt.executeQuery();

                int idKategori;
                if (rs.next()) {
                    idKategori = rs.getInt("id_kategori");
                } else {
                    String insertKategori = "INSERT INTO kategori (nama_kategori) VALUES (?)";
                    PreparedStatement insertStmt = conn.prepareStatement(insertKategori, Statement.RETURN_GENERATED_KEYS);
                    insertStmt.setString(1, kategoriStr);
                    insertStmt.executeUpdate();
                    
                    ResultSet generatedKeys = insertStmt.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        idKategori = generatedKeys.getInt(1);
                    } else {
                        throw new SQLException("Gagal mengambil ID kategori baru.");
                    }
                }

                // Update tugas
                String updateSql = "UPDATE tugas SET judul = ?, deskripsi = ?, deadline = ?, id_kategori = ? WHERE id_tugas = ?";
                PreparedStatement updateStmt = conn.prepareStatement(updateSql);
                updateStmt.setString(1, judul);
                updateStmt.setString(2, deskripsi);
                updateStmt.setDate(3, new java.sql.Date(deadline.getTime()));
                updateStmt.setInt(4, idKategori);
                updateStmt.setInt(5, idTugas);

                int rows = updateStmt.executeUpdate();
                if (rows > 0) {
                    conn.commit();
                    JOptionPane.showMessageDialog(this, "Tugas berhasil diperbarui!");
                    new admin.tugas(username).setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui tugas!");
                    conn.rollback();
                }
            } catch (SQLException e) {
                e.printStackTrace();
                try {
                    if (conn != null) conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            } finally {
                try {
                    if (conn != null) conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_roundedButton3ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(EditTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(EditTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(EditTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(EditTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Gunakan ID dummy untuk testing

            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateDeadline;
    private com.mycompany.tindaklanjutku.custom.RoundedTextField deskripsiField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.mycompany.tindaklanjutku.custom.RoundedTextField judulField;
    private com.mycompany.tindaklanjutku.custom.RoundedTextField kategori1;
    private com.mycompany.tindaklanjutku.custom.panelCustom panelCustom1;
    private com.mycompany.tindaklanjutku.custom.panelCustom panelCustom2;
    private com.mycompany.tindaklanjutku.custom.RoundedButton roundedButton3;
    // End of variables declaration//GEN-END:variables
    }
